import type { Metadata } from "next";
import {Inter, Roboto ,Poppins} from "next/font/google";
import "./globals.css";
import Footer from "./component/Footer";
import Header, { Header2, Header3 } from "./component/Header";

const inter = Inter ({ subsets :["latin"]});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'], // Add required weights here
});
const poppins = Poppins ({ subsets :["latin"] , weight : ['400', '700', '600']});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${roboto.className} ${poppins.className} antialiased`}
        
      ><Header />
      <Header2 />
      <Header3 />
        {children}
        <Footer />
      </body>
    </html>
  );
}
